name: GitHub Actions - Workflow dispatch Template - Choice
run-name: Running - ${{ github.event_name }}
on:
  workflow_dispatch:
    inputs:
      browser:
        description: Select Browser
        type: string 
jobs:
  on-workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Comments
        run: |
          echo "Comments  WORKFLOW dispatch - ${{inputs.browser}}"