name: GitHub Actions - Dependencies test Template
run-name: Running - Dependencies test Template
on: [push, workflow_dispatch]

jobs:
  test_unit:
    runs-on: ubuntu-latest
    steps:
      - name: Comments
        run: |
          echo "Execute unit test"

  test_api:
    # needs: test_unit
    runs-on: ubuntu-latest
    steps:
      - name: Comments
        run: |
          echo "Run api tests"

  test_ui:
    needs: [test_unit, test_api]
    runs-on: ubuntu-latest
    steps:
      - name: Comments
        run: |
          echo "Run UI tests"