name: GitHub Actions - Pull Request Basic Template
run-name: Running - ${{ github.event_name }}
on: [pull_request]
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comments
        run: |
          echo "Comments PULL REQUEST WORKFLOW - Basic"