name: GitHub Actions - Pull Request General
run-name: Running - ${{ github.event_name }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
    branches:
      - main
    paths:
      - '**.txt'
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comments
        run: |
          echo "Comments PULL REQUEST WORKFLOW - General"