name: Github actions - Push Template Basic
run-name: Running - ${{ github.event_name }}
on:
  push:
    branches-ignore:
      - main
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comments
        run: | 
          echo "Comment on workflow - new branch PUSH"