name: GitHub Actions - Configuring Repository variable
run-name: Running - Var Repo Config
on: [push, workflow_dispatch]
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comments
        run: |
          echo "${{ vars.var_test }}"