name: Github actions - Push Branch Template 
run-name: Running - ${{ github.event_name }}
on:
  push:
    branches:
      - develop
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comments
        run: | 
          echo "Comment on branch develop PUSH2"