name: GitHub Actions - Configuration Repository secret
run-name: Running - Secret Repo Config
on: [push, workflow_dispatch]
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comments
        run: |
          echo "${{ secrets.test_secret }}"