name: GitHub Actions - Workflow dispatch Template - Choice
run-name: Running - ${{ github.event_name }}
on:
  workflow_dispatch:
    inputs:
      tags:
        description: Select the tag
        type: choice
        options:
          - tag_1
          - tag_2
          - tag_3
        default: tag_2
        required: true
    
jobs:
  on-workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Comments
        run: |
          echo "Comments PULL REQUEST WORKFLOW - ${{inputs.tags}}"