name: Github actions - Push - Branch Ignore Template
run-name: Running - ${{ github.event_name }}
on:
  push:
    branches-ignore:
      - main
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comments
        run: | 
          echo "Comment on workflow - branches ignore"