name: GitHub Actions - Managing errors
run-name: Running - Managing errors
on: [push, workflow_dispatch]

jobs:
  
  job_1_error:
    runs-on: ubuntu-latest
    steps:
      - name: Comments
        run: |
          echo Comments before error 
          exit 1
      - name: Comments
        run: |
          echo Comments after error