name: GitHub Actions - Worflow run muklti-workflows
run-name: Running - Workflow run multi-workflows
on:
  workflow_run:
    workflows: [GitHub Actions - Trigger 1, GitHub Actions - Trigger 2]
    types: [completed]
    branches: [main]
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comments
        run: |
          echo "Workflow has been triggered" 