name: Github actions - Push General
run-name: Running - ${{ github.event_name }}
on:
  push:
    branches:
    - master
    - develop
    # branches-ignore:
    # - 'release/**'
    paths:
      - '**.txt'
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comments
        run: | 
          echo "Comment on workflow - ON PUSH"